name: 'Task Completed Checker'
description: 'Based on kentaro-m/task-completed-checker-action'
author: 'tmakuch'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'green'
